# CircleCI 2.0 configuration file for running Python on macOS
#
# Based on these v1.0 steps:
# https://pewpewthespells.com/blog/building_python_on_circleci.html
#
version: 2

jobs:
  build:
    macos:
      xcode: "9.3.0"

    working_directory: ~/repo

    steps:
      # Get the source.
      - checkout

      # Run tests with tox without any cached dependencies.
      - run:
          name: run tests
          command: |
            export PATH=/usr/local/bin:$PATH:/Users/distiller/Library/Python/2.7/bin
            python --version
            pip install -q --user --ignore-installed --upgrade virtualenv
            pip install -q tox --user
            tox -r -e py27-alldeps-nocov-posix twisted


# For this is a simple workflow with a single stage.
workflows:
  version: 2
  test:
    jobs:
      - build
