# CircleCI 2.0 configuration file for running Python on macOS.
#
# Email notifications are configured only from web.
# See "Email Preferences by Organization" in
# https://circleci.com/account/notifications
#
# Based on these v1.0 steps:
# https://pewpewthespells.com/blog/building_python_on_circleci.html
#
# This uses the v2 workflows and a separate commit status is sent for each
# job.
#
version: 2

jobs:
  static_checkers:
    working_directory: ~/static-checkers
    docker:
      - image: circleci/python:2.7
    steps:
      # Get the source.
      - checkout

      - run:
          name: Prepare the environment.
          command: |
            python --version
            pip install -q --user --ignore-installed --upgrade virtualenv
            pip install -q tox --user

      # Run each checker in a separate step.
      - run:
          name: Check newsfragment.
          command: |
            export PATH=~/.local/bin:$PATH
            tox -r -e newsfragment
      - run:
          name: Check manifest-checker.
          command: |
            tox -r -e manifest-checker
      - run:
          name: Check pyflakes.
          command: |
            tox -r -e pyflakes
      - run:
          name: Check the narrative documentation.
          command: |
            tox -r -e narrativedocs
      - run:
          name: Check the API documentation.
          command: |
            tox -r -e apidocs

  macos_py27_default_reactor:
    macos:
      # We don't use the xcode, but we need to put something here.
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      # Get the source.
      - checkout

      - run:
          name: Prepare the macOS environment.
          command: |
            export PATH=/usr/local/bin:$PATH:/Users/distiller/Library/Python/2.7/bin
            python --version
            pip install -q --user --ignore-installed --upgrade virtualenv
            pip install -q tox --user

      # Run tests with tox without any cached dependencies.
      - run:
          name: Test with the default reactor.
          command: |
            export PATH=/usr/local/bin:$PATH:/Users/distiller/Library/Python/2.7/bin
            tox -r -e py27-alldeps-withcov-posix twisted


# First we run the static checkers, and only if they pass we spin the macOS.
# in this way we should save some macOS minutes.
workflows:
  version: 2
  all-tests:
    jobs:
      - static_checkers
      - macos_py27_default_reactor:
          requires:
            - static_checkers
