# CircleCI 2.0 configuration file for running Python on macOS.
#
# Based on these v1.0 steps:
# https://pewpewthespells.com/blog/building_python_on_circleci.html
#
version: 2

jobs:
  build:
    macos:
      # We don't use the xcode, but we need to put something here.
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      # Get the source.
      - checkout

      - run:
          name: prepare environment
          command: |
            export PATH=/usr/local/bin:$PATH:/Users/distiller/Library/Python/2.7/bin
            python --version
            pip install -q --user --ignore-installed --upgrade virtualenv
            pip install -q tox --user

      # Run tests with tox without any cached dependencies.
      - run:
          name: run tests
          command: |
            export PATH=/usr/local/bin:$PATH:/Users/distiller/Library/Python/2.7/bin
            tox -r -e py27-alldeps-withcov-posix twisted
